### ISSUE TITLE
Broken link and typo

### ISSUE THREAD

**Issue by wfalkwallace** [adicu/learn-webdev#42]
http://learn.adicu.com/python/ "fork me on github" banner links here and shouldn't :disappointed:
the learn python guide also confusingly says: 

> ```
> # Notice the capital letters!
> True
> False
> ```
> 
> We can negate these values using the word not:
> 
> ```
> not True # False
> not False # true
> ```

_Notice_ the lower-case letter?

**Comment by schlosser** [comment]
http://learn.adicu.com/python now has the correct github link and the typo is fixed

Thanks for submitting this issue!

**Comment by wfalkwallace** [comment]
Thanks, Dan!
